from __future__ import annotations

from enum import Enum

__NAMESPACE__ = "http://knx.org/xml/project/11"


class ResourceName(Enum):
    MANAGEMENT_STYLE = "ManagementStyle"
    DEVICE_MANUFACTURER_ID = "DeviceManufacturerId"
    DEVICE_BUS_VOLTAGE = "DeviceBusVoltage"
    DEVICE_PEI_TYPE = "DevicePeiType"
    GROUP_ADDRESS_TABLE_LOAD_CONTROL = "GroupAddressTableLoadControl"
    GROUP_ADDRESS_TABLE_LOAD_STATUS = "GroupAddressTableLoadStatus"
    GROUP_ADDRESS_TABLE_PTR = "GroupAddressTablePtr"
    GROUP_ADDRESS_TABLE = "GroupAddressTable"
    GROUP_ASSOCIATION_TABLE_LOAD_CONTROL = "GroupAssociationTableLoadControl"
    GROUP_ASSOCIATION_TABLE_LOAD_STATUS = "GroupAssociationTableLoadStatus"
    GROUP_ASSOCIATION_TABLE_PTR = "GroupAssociationTablePtr"
    GROUP_ASSOCIATION_TABLE = "GroupAssociationTable"
    GROUP_OBJECT_TABLE_PTR = "GroupObjectTablePtr"
    GROUP_OBJECT_TABLE = "GroupObjectTable"
    GROUP_FILTER_TABLE_PTR = "GroupFilterTablePtr"
    GROUP_FILTER_TABLE = "GroupFilterTable"
    APPLICATION_ID = "ApplicationId"
    APPLICATION_LOAD_CONTROL = "ApplicationLoadControl"
    APPLICATION_LOAD_STATUS = "ApplicationLoadStatus"
    APPLICATION_RUN_CONTROL = "ApplicationRunControl"
    APPLICATION_RUN_STATUS = "ApplicationRunStatus"
    PEIPROG_ID = "PeiprogId"
    PEIPROG_LOAD_CONTROL = "PeiprogLoadControl"
    PEIPROG_LOAD_STATUS = "PeiprogLoadStatus"
    PEIPROG_RUN_CONTROL = "PeiprogRunControl"
    PEIPROG_RUN_STATUS = "PeiprogRunStatus"
    APPLICATION_PEI_TYPE = "ApplicationPeiType"
    RE_CONFIG = "ReConfig"
    INDIVIDUAL_ADDRESS = "IndividualAddress"
    DOMAIN_ADDRESS = "DomainAddress"
    FREQUENCY_CHANNEL = "FrequencyChannel"
    SENSITIVITY = "Sensitivity"
    HARDWARE_CONFIG1 = "HardwareConfig1"
    HARDWARE_CONFIG2 = "HardwareConfig2"
    HARDWARE_CONFIG3 = "HardwareConfig3"
    HARDWARE_CONFIG4 = "HardwareConfig4"
    DEVICE_ORDER_ID = "DeviceOrderId"
    DEVICE_SERIAL_NUMBER = "DeviceSerialNumber"
    PROGRAMMING_MODE = "ProgrammingMode"
    POLLING_GROUP_SETTINGS = "PollingGroupSettings"
    MANAGEMENT_DESCRIPTOR01 = "ManagementDescriptor01"
    RUN_ERROR = "RunError"
    LC_CONFIG = "LcConfig"
    LC_GRP_CONFIG = "LcGrpConfig"
    LC_ERROR = "LcError"
    LC_MODE = "LcMode"
    GROUP_OBJECT_TABLE_LOAD_CONTROL = "GroupObjectTableLoadControl"
    GROUP_OBJECT_TABLE_LOAD_STATUS = "GroupObjectTableLoadStatus"
    GROUP_ACKNOWLEDGE_TABLE = "GroupAcknowledgeTable"
    HARDWARE_TYPE = "HardwareType"
    FIRMWARE_VERSION = "FirmwareVersion"
    MANUFACTURER_DATA = "ManufacturerData"
    APPLICATION_DATA_PTR = "ApplicationDataPtr"
    PEIPROG_DATA_PTR = "PeiprogDataPtr"
    GROUP_ADDRESS_TABLE_STAMP = "GroupAddressTableStamp"
    GROUP_ASSOCIATION_TABLE_STAMP = "GroupAssociationTableStamp"
    GROUP_OBJECT_TABLE_STAMP = "GroupObjectTableStamp"
    GROUP_FILTER_TABLE_STAMP = "GroupFilterTableStamp"
    APPLICATION_STAMP = "ApplicationStamp"
    PEIPROG_STAMP = "PeiprogStamp"
    MAX_APDU_LENGTH = "MaxApduLength"
    GROUP_FILTER_TABLE_LOAD_CONTROL = "GroupFilterTableLoadControl"
    GROUP_FILTER_TABLE_LOAD_STATUS = "GroupFilterTableLoadStatus"
    MAIN_LC_CONFIG = "MainLcConfig"
    SUB_LC_CONFIG = "SubLcConfig"
    MAIN_LC_GRP_CONFIG = "MainLcGrpConfig"
    SUB_LC_GRP_CONFIG = "SubLcGrpConfig"
    COUPL_SERV_CONTROL = "CouplServControl"
    MAX_ROUTING_APDU_LENGTH = "MaxRoutingApduLength"
